name: places
description: A new Flutter project.

publish_to: 'none' 

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3

dev_dependencies:
  dart_code_metrics: ^4.15.2
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.5.0

flutter:
  uses-material-design: true

  assets: 
    - res/

  fonts:
    - family: Roboto
      fonts: 
        - asset: res/Roboto-Regular.ttf
